---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: http-app-1
  namespace: default

spec:
  parentRefs:
    - name: traefik-gateway

  hostnames:
    - whoami

  rules:
    - backendRefs:
        - name: whoami
          port: 80
          weight: 3

        - name: nginx
          port: 80
          weight: 1
